import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import ThemeProvider from '@/providers/ThemeProvider';
import Navbar from '@/components/Mixins/Navbar';
import Footer from '@/components/Mixins/Footer';

const fontSans = FontSans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <Navbar />

          <main className='min-h-screen flex items-center justify-center mx-auto'>{children}</main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
